# Generated by Django 6.0.3 on 2026-04-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=200)),
                ('codigo_turma', models.CharField(max_length=20)),
            ],
        ),
    ]
